# Data Science Package

In [2]:
# DS Packages are used for performing Data Analytics

# There are various data science packages
# 1) Numpy
# 2) Pandas
# 3) Matplotlib
# 4) Seaborn
# 5) Plotly

# Numpy 

## Numpy -  Array operation & Math computing

In [5]:
# List Data Type
# 1) Numpy is faster and more effecient than List (Data Type)
# 2) Provided build in mathematical functions (sum, min, max,mean, std, var)
# 3) Essential for data science, machine learning and numerical computing

# Install Numpy

In [7]:
# Install Numpy
# when we install a DS package -> pip install name_of_the_package

# pip install numpy
# Conda install numpy

In [8]:
import numpy as np

In [9]:
# Create Arrays
# 1D, 2D, 3D Arrays

a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [10]:
a2 = np.array([2,4,6])
a2

array([2, 4, 6])

In [11]:
a3 = np.array ([3,5,6])
a3

array([3, 5, 6])

In [12]:
# 2D Array

b1 = np.array([[1,2,3],[4,5,6]])
b1

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
c1 = np.array([[4,5,6,10,11],[7,8,9,10,11]])
c1

array([[ 4,  5,  6, 10, 11],
       [ 7,  8,  9, 10, 11]])

In [14]:
# Array properties

print(c1.shape) # Shape of my Array -> 2 Rows and 5 column
print(c1.ndim) # Total no. of Dimensions
print(c1.size) # Total no. of elements

(2, 5)
2
10


In [15]:
# Create Special Arrays
# Creating a 3x3 Matric of zeros
print(np.zeros((3,3))) 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
(np.zeros((3,3)))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
(np.zeros((4,3)))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
# Identity Matrix - > Diagonal element is 1
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.full(((3,5)),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [21]:
# Array Properties

a1.shape  # Shape of your array (Row,Column)
a1.ndim  # Dimension of the Array -> 1D or 2D
a1.size # Total no. of elements

5

In [22]:
# Conclusion
# Special arrays (Matrix)
np.zeros((3,3)) # Create a matrix of all zeros
np.ones((3,3))  # Create a matrix of all zeros
np.eye(3)       # Create an identity matrix
np.full((3,3),7)# Fill 3X3 Matrix by 7

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [23]:
# 2D Array
a1 = np.array ([[1,2,3],[4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
# Mathematical Calculations in python

print(a1.sum()) # Sum all the elements
print(a1.mean()) # Mean or Avg
print(a1.min()) # Minimum value
print(a1.max()) # Maximm value
print(a1.std()) #Standard deviation
print(a1.var()) #Variance = square of standard deviation (1.707825127659933 ** 2 = 2.9166666666666665)
print(a1.sum(axis = 0)) # Summed column wise
print(a1.sum(axis = 1)) # Summed row wise


21
3.5
1
6
1.707825127659933
2.9166666666666665
[5 7 9]
[ 6 15]


In [25]:
# Basic array Operation

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b) # Addtion on Array
print(a-b) # Subtraction on Array
print(a*b) # Multiplication on Array
print(a/b) # Division on Array

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [26]:
# Generate Random Numbers
# This comes very handy when we work with Monte carlo simulation

np.random.rand(3,3) # Generate random number between 0 and 1

array([[0.46759522, 0.00481482, 0.7127386 ],
       [0.9190046 , 0.06607732, 0.63146574],
       [0.81713256, 0.87662658, 0.95179223]])

In [27]:
np.random.randn(3,3) # Normally Distributed

array([[ 0.79844998,  0.28329335, -1.26050048],
       [ 1.18558176,  1.52259584, -0.64409098],
       [-1.09875475, -0.14124456, -1.72225554]])

In [28]:
np.random.randint(1,100,(3,3)) # Generated Random integer number b/w 1 and 100

array([[55, 12, 15],
       [38, 90, 87],
       [44, 16, 86]])

In [29]:
# Reshaping and Flattening Array

a1 = np.array([[1,2,3],[4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
a1.shape

(2, 3)

In [31]:
# Reshape the arrey
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
# Flattent the Array
a1.flatten()

array([1, 2, 3, 4, 5, 6])

In [33]:
# Generate Sequence of Numbers

# start = 1
# stop = 10-1 =1
# jump/step = 1

np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [35]:
np.arange(1,10,3)

array([1, 4, 7])

In [36]:
# Generate number of equal space
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [37]:
np.linspace(1,1,5)

array([1., 1., 1., 1., 1.])

In [38]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [39]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [83]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [41]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [42]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

# Thank you!